// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:flutter/widgets.dart';
import 'package:routefly/routefly.dart';

import 'ui/auth/login/login_page.dart' as a9;
import 'ui/auth/recover_password/confirm_password/confirm_password_page.dart'
    as a7;
import 'ui/auth/recover_password/otp/otp_page.dart' as a5;
import 'ui/auth/recover_password/send_email/send_email_page.dart' as a6;
import 'ui/auth/register/register_page.dart' as a8;
import 'ui/generic_pages/feedback_error_page.dart' as a1;
import 'ui/generic_pages/feedback_success_page.dart' as a0;
import 'ui/post/feed/feed_page.dart' as a3;
import 'ui/post/new_post/new_post_page.dart' as a4;
import 'ui/splash/splash_page.dart' as a2;

Route b0Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a0.FeedbackSuccessPage());
Route b1Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a1.FeedbackErrorPage());
Route b2Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a2.SplashPage());
Route b3Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a3.FeedPage());
Route b4Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a4.NewPostPage());
Route b5Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a5.OtpPage());
Route b6Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a6.SendEmailPage());
Route b7Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a7.ConfirmPasswordPage());
Route b8Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a8.RegisterPage());
Route b9Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a9.LoginPage());
