name: backend
description: Flutterando APP.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

dependencies:
  vaden: ^0.0.9

dev_dependencies:
  build_runner: ^2.4.14
  vaden_class_scanner: ^0.0.9
